# Generated by Django 6.0.2 on 2026-02-25 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movie_review_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="review",
            name="rating",
            field=models.SmallIntegerField(
                choices=[
                    (1, "Terrible"),
                    (2, "Bad"),
                    (3, "Average"),
                    (4, "Good"),
                    (5, "Excellent"),
                ]
            ),
        ),
        migrations.DeleteModel(
            name="Rating",
        ),
    ]
