# Generated by Django 6.0.2 on 2026-02-27 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "movie_review_app",
            "0003_alter_comment_options_alter_review_options_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="movie",
            name="created_at",
        ),
    ]
