# Generated by Django 6.0.2 on 2026-02-27 18:14

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movie_review_app", "0004_remove_movie_created_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="movie",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
