# Generated by Django 6.0.5 on 2026-06-04 18:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_review_app', '0005_movie_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='viewer',
            name='favourite_movie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='viewers', to='movie_review_app.movie'),
        ),
    ]
